spring.application.name=hwss1001
#config datasource
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/db_jpa_hwss1001
spring.datasource.username=postgres
spring.datasource.password=123456
#config JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#config API
cloud_name=dnsheem26
api-key=161853372289159
api_secret=${API_SECRET}